### ISSUE TITLE
Duplicate error

### ISSUE THREAD

**Issue by sarahmovementecon** [sfirke/surveymonkey#115]
I have been using your package for about a month and am really appreciating it so much. Today I ran my code to pull data from survey monkey using your package and I received the following error:

Error: There are duplicated rows in the responses.
To proceed and retain duplicates, re-run this function with fix_duplicates = 'keep'
To proceed with dropped duplicates, re-run with fix_duplicates = 'drop'
If this is unexpected - file a bug report at https://github.com/mattroumaya/surveymonkey/issues

I tried to add the function as another line as shown below, but that did not work.

survey_english <- 402595717 %>%
  fetch_survey_obj %>%
  parse_survey %>% 
  strip_html %>%
  fix_duplicates = 'keep'

I am pulling data from two different surveys and only received the error on one of the surveys. The survey that generated the error was also hit by bots last week and has a really large number of rows, but from what I have seen they are not duplicated. 

Please let me know if this is a known issue that I can easily resolve. I really hope to continuing using this very useful package.

**Comment by mattroumaya** [comment]
Hey @sarahmovementecon! Glad you are finding the package useful. 

It's hard to know why your survey might be pulling duplicates, but if you know you want to keep them, you can do so like this: 

```r
survey_english <- 402595717 %>%
fetch_survey_obj %>%
parse_survey(fix_duplicates = 'keep') %>%
strip_html
```
`fix_duplicates` is an argument to the `parse_survey()` function, so that's why the code you have probably wasn't working. 

Let me know if this resolves the error!

**Comment by sarahmovementecon** [comment]
Hi Matt,

Thank you so much for your quick reply. I did not get the same error, but
am now receiving a different error message:

Error in `dplyr::bind_cols()`:! Can't recycle `survey_id` (size 12678)
to match `..41786` (size 2).


Any ideas on what could be causing this? This had been working fine
previously and nothing has changed about the survey, except that I
have a lot more observations now and also added some new collectors.
My code is also still working fine on a separate survey that I have
been pulling data from. I really appreciate your help with this!


Sarah

**Comment by mattroumaya** [comment]
Hi Sarah - sorry for the late reply! Were you able to resolve this?

**Comment by mattroumaya** [comment]
Closing out for now, but please re-open if this pops up again!

**Comment by mfernandes3** [comment]
Same error for me! Works for some survey IDs but for others I get this. Tried `keep` and `drop` here `parse_survey(fix_duplicates = 'keep')`
