### ISSUE TITLE
Error with parse_survey id = 152868972

### ISSUE THREAD

**Issue by dpashouwer** [sfirke/surveymonkey#38]
Old survey from 2018 that I'm trying to access. Keep running into the error: "Error: Argument 2 must be length 1, not 0"

![image](https://user-images.githubusercontent.com/4881370/63363345-a8d6b280-c330-11e9-8ee2-98c3f43859f4.png)

**Comment by sfirke** [comment]
Survey id `188182243` has actual `tag_data`, which caused breakage.  I am now intentionally dropping the tag data for now.  Specifically it's on page 4, Q5 of that survey.
